version: '3'
services:
  column-generator-frontend:
    build:
      context: ""
      dockerfile: Dockerfile
    # unique name
    container_name: ${CONTAINER_NAME}
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    env_file:
      - .env
    restart: always
  column-generator-backend:
    build:
      context: ""
      dockerfile: server/Dockerfile
    # unique name
    container_name: ${BACKEND_CONTAINER_NAME}
    volumes:
      - './keys:/app/keys'
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    env_file:
      - .env
    restart: always